---
# Host-specific overrides
hostname: "dev.deusasrainhas.local"
nfs_storage_path: /storage/disks/deusasrainhas/dev
nfs_mount_path: /home/ubuntu/storage
storage_mounts:
  - src: "{{ nfs_storage_server }}:{{ nfs_storage_path }}"
    dest: "{{ nfs_mount_path }}"
    fstype: "nfs"
    opts: "rw,defaults"
    state: "mounted"
