---
# Host-specific overrides
hostname: "dns.rosa.local"
nfs_storage_path: /storage/disks/rosa/dns
nfs_mount_path: /home/{{ansible_user}}/storage
storage_mounts:
  - src: "{{ nfs_storage_server }}:{{ nfs_storage_path }}"
    dest: "{{ nfs_mount_path }}"
    fstype: "nfs"
    opts: "rw,defaults"
    state: "mounted"
