---
# hosts-specific overrides
hostsname: "proxmox.rosa.local"

nfs_exports:
  - "###### NFS hosts SHARES ######"
  - "# prd.rosa.local"
  - "/storage/hosts/deusasrainhas/prd 192.168.70.75/32(rw,sync,no_root_squash,no_subtree_check)"
  - "#"
  - "#"
  - "# dev.rosa.local
  - "/storage/hosts/deusasrainhas/dev 192.168.70.76/32(rw,sync,no_root_squash,no_subtree_check)"
  - "#"
  - "#"
  - "#dns.rosa.local"
  - "/storage/hosts/deusasrainhas/vpn 192.168.70.8/32(rw,sync,no_root_squash,no_subtree_check)"
  - "#"
  - "#"
  - "# stg.rosa.local"
  - "/storage/hosts/deusasrainhas/stg 192.168.70.79/32(rw,sync,no_root_squash,no_subtree_check)"
  - "#"
  - "#"
  - "# vpn.rosa.local
  - "/storage/hosts/deusasrainhas/vpn 192.168.70.6/32(rw,sync,no_root_squash,no_subtree_check)"

nfs_shares:
  - "/storage/hosts/rosa/vpn"
  - "/storage/hosts/rosa/dns"
  - "/storage/hosts/deusasrainhas/dev"
  - "/storage/hosts/deusasrainhas/prd"
  - "/storage/hosts/deusasrainhas/stg"

