- name: Setup local DEV Server
  hosts: dev.deusasrainhas.local
  become: yes
  become_method: sudo
  
  vars_files:
    - host_vars/dev.deusasrainhas.local.yml
  
  roles:
    - common
    - docker
    - mounts
    - developer
    - ai-claude
    