- name: Setup local PRD Server
  hosts: prd.deusasrainhas.local
  become: yes
  become_method: sudo
  
  vars_files:
    - host_vars/prd.deusasrainhas.local.yml
  
  roles:
    - common
    - docker
    - mounts
    - ai-claude