- name: Setup local DNS Server
  hosts: dns.deusasrainhas.local
  become: yes
  become_method: sudo
  
  vars_files:
    - host_vars/dns.deusasrainhas.local.yml
  
  roles:
    - common
    - docker
    - mounts
